*** empty log message ***
git-svn-id: svn://localhost:7744/trunk/alps@2317 3665984a-f8b0-4bb5-b30c-cdcaecbe7ced

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -463,7 +463,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT LIB_VERSION_INFO docdir SRC_DIR ALPS_XML_DIR build build_cpu build_vendor build_os host host_cpu host_vendor host_os COMPILER CPPFLAGS CFLAGS CXXFLAGS CC LDFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CXX ac_ct_CXX CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE CPP CXXCPP EGREP LN_S ECHO AR ac_ct_AR RANLIB ac_ct_RANLIB F77 FFLAGS ac_ct_F77 LIBTOOL BOOST_CPPFLAGS BOOST_LDFLAGS BOOST_LIBS BOOST_INCDIR BOOST_DIR BOOST_SRCDIR OBJ_PTHREAD LIB_PTHREAD EXAMPLE_PTHREAD HDF5_CPPFLAGS HDF5_LDFLAGS HDF5_LIBS LAPACK_CPPFLAGS LAPACK_LDFLAGS LAPACK_LIBS SQLITE_CPPFLAGS SQLITE_LDFLAGS SQLITE_LIBS XML_CPPFLAGS XML_LDFLAGS XML_LIBS LIB_MPI MPI_CPPFLAGS MPI_LDFLAGS MPI_LIBS OBJ_MPI EXAMPLE_MPI BOOST_USER_CONFIG_H ac_cv_prog_doxygen DOXYGEN ac_cv_prog_xsltproc XSLTPROC ac_cv_prog_java JAVA DOCBOOK_DTD_DIR DOCBOOK_XSL_DIR FOP_DIR FOP_BIN FOP_OPTS JAVA_OPTS BASE_CPPFLAGS BASE_LDFLAGS BASE_LIBS abs_top_srcdir ALPS_FULL_TRUE ALPS_FULL_FALSE ALPS_LIGHT_TRUE ALPS_LIGHT_FALSE BOOST_1_32_TRUE BOOST_1_32_FALSE BOOST_1_33_TRUE BOOST_1_33_FALSE BOOST_1_34_TRUE BOOST_1_34_FALSE BOOST_CVS_TRUE BOOST_CVS_FALSE BUILD_BOOST_TRUE BUILD_BOOST_FALSE BUILD_BOOST_SIGNALS_TRUE BUILD_BOOST_SIGNALS_FALSE BUILD_BOOST_THREAD_TRUE BUILD_BOOST_THREAD_FALSE BUILD_DOC_TRUE BUILD_DOC_FALSE BUILD_PDF_TRUE BUILD_PDF_FALSE BUILD_LIBHEAP_TRUE BUILD_LIBHEAP_FALSE BUILD_ARCHIVE_TRUE BUILD_ARCHIVE_FALSE HAVE_MPI_TRUE HAVE_MPI_FALSE LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT LIB_VERSION_INFO docdir SRC_DIR ALPS_XML_DIR build build_cpu build_vendor build_os host host_cpu host_vendor host_os COMPILER CPPFLAGS CFLAGS CXXFLAGS CC LDFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CXX ac_ct_CXX CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE CPP CXXCPP EGREP LN_S ECHO AR ac_ct_AR RANLIB ac_ct_RANLIB F77 FFLAGS ac_ct_F77 LIBTOOL BOOST_CPPFLAGS BOOST_LDFLAGS BOOST_LIBS BOOST_INCDIR BOOST_DIR BOOST_SRCDIR OBJ_PTHREAD LIB_PTHREAD EXAMPLE_PTHREAD HDF5_CPPFLAGS HDF5_LDFLAGS HDF5_LIBS LAPACK_CPPFLAGS LAPACK_LDFLAGS LAPACK_LIBS SQLITE_CPPFLAGS SQLITE_LDFLAGS SQLITE_LIBS XML_CPPFLAGS XML_LDFLAGS XML_LIBS LIB_MPI MPI_CPPFLAGS MPI_LDFLAGS MPI_LIBS OBJ_MPI EXAMPLE_MPI BOOST_USER_CONFIG_H ac_cv_prog_doxygen DOXYGEN ac_cv_prog_xsltproc XSLTPROC ac_cv_prog_java JAVA DOCBOOK_DTD_DIR DOCBOOK_XSL_DIR FOP_DIR FOP_BIN FOP_OPTS JAVA_OPTS BASE_CPPFLAGS BASE_LDFLAGS BASE_LIBS abs_top_srcdir ALPS_FULL_TRUE ALPS_FULL_FALSE ALPS_LIGHT_TRUE ALPS_LIGHT_FALSE BOOST_1_32_TRUE BOOST_1_32_FALSE BOOST_1_33_TRUE BOOST_1_33_FALSE BOOST_1_34_TRUE BOOST_1_34_FALSE BOOST_CVS_TRUE BOOST_CVS_FALSE BUILD_BOOST_TRUE BUILD_BOOST_FALSE BUILD_BOOST_SIGNALS_TRUE BUILD_BOOST_SIGNALS_FALSE BUILD_BOOST_THREAD_TRUE BUILD_BOOST_THREAD_FALSE BUILD_BOOST_WCHAR_TRUE BUILD_BOOST_WCHAR_FALSE BUILD_DOC_TRUE BUILD_DOC_FALSE BUILD_PDF_TRUE BUILD_PDF_FALSE BUILD_LIBHEAP_TRUE BUILD_LIBHEAP_FALSE BUILD_ARCHIVE_TRUE BUILD_ARCHIVE_FALSE HAVE_MPI_TRUE HAVE_MPI_FALSE LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -1069,6 +1069,8 @@ Optional Packages:
   --with-boost-all        compile all optional Boost libraries
   --with-boost-signals    compile Boost::signals library
   --with-boost-thread     compile boost::thread library
+  --without-boost-wchar   compile without wchar support in boost::regex and
+                          boost::serialization libraries
   --with-pthread          use pthread library
   --with-hdf5=DIR         use HDF5 library
   --with-atlas=LIBS       use ATLAS Library
@@ -7025,7 +7027,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 7028 "configure"' > conftest.$ac_ext
+  echo '#line 7030 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -7687,7 +7689,7 @@ fi
 
 
 # Provide some information about the compiler.
-echo "$as_me:7690:" \
+echo "$as_me:7692:" \
      "checking for Fortran 77 compiler version" >&5
 ac_compiler=`set X $ac_compile; echo $2`
 { (eval echo "$as_me:$LINENO: \"$ac_compiler --version </dev/null >&5\"") >&5
@@ -8750,11 +8752,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:8753: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:8755: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:8757: \$? = $ac_status" >&5
+   echo "$as_me:8759: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -9018,11 +9020,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:9021: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:9023: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:9025: \$? = $ac_status" >&5
+   echo "$as_me:9027: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -9122,11 +9124,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:9125: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:9127: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:9129: \$? = $ac_status" >&5
+   echo "$as_me:9131: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -11467,7 +11469,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 11470 "configure"
+#line 11472 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -11567,7 +11569,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 11570 "configure"
+#line 11572 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -13907,11 +13909,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:13910: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:13912: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:13914: \$? = $ac_status" >&5
+   echo "$as_me:13916: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -14011,11 +14013,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:14014: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:14016: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:14018: \$? = $ac_status" >&5
+   echo "$as_me:14020: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -15581,11 +15583,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:15584: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:15586: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:15588: \$? = $ac_status" >&5
+   echo "$as_me:15590: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -15685,11 +15687,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:15688: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:15690: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:15692: \$? = $ac_status" >&5
+   echo "$as_me:15694: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -17888,11 +17890,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:17891: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:17893: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:17895: \$? = $ac_status" >&5
+   echo "$as_me:17897: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -18156,11 +18158,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:18159: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:18161: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:18163: \$? = $ac_status" >&5
+   echo "$as_me:18165: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -18260,11 +18262,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:18263: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:18265: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:18267: \$? = $ac_status" >&5
+   echo "$as_me:18269: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -21075,6 +21077,19 @@ if test "${with_boost_thread+set}" = set; then
       ac_cv_boost_thread=no
     else
       ac_cv_boost_thread=yes
+    fi
+
+
+fi;
+
+# Check whether --with-boost-wchar or --without-boost-wchar was given.
+if test "${with_boost_wchar+set}" = set; then
+  withval="$with_boost_wchar"
+
+    if test "x$withval" = "xno"; then
+      ac_cv_boost_wchar=no
+    else
+      ac_cv_boost_wchar=yes
     fi
 
 
@@ -28486,6 +28501,15 @@ echo "${ECHO_T}no" >&6
   fi
 fi
 
+# check whether boost::thread is compiled
+if test "$ac_cv_use_precompiled_boost" = yes; then :; else
+  echo "$as_me:$LINENO: checking for wchar support in boost::regex and boost::serialization" >&5
+echo $ECHO_N "checking for wchar support in boost::regex and boost::serialization... $ECHO_C" >&6
+  test -z "$ac_cv_boost_wchar" && ac_cv_boost_wchar=yes
+  echo "$as_me:$LINENO: result: $ac_cv_boost_wchar" >&5
+echo "${ECHO_T}$ac_cv_boost_wchar" >&6
+fi
+
 # check whether Boost::configure is used or not
 # Check whether --enable-boost-config or --disable-boost-config was given.
 if test "${enable_boost_config+set}" = set; then
@@ -29159,6 +29183,16 @@ fi
 
 
 
+if test "$ac_cv_boost_wchar" = yes; then
+  BUILD_BOOST_WCHAR_TRUE=
+  BUILD_BOOST_WCHAR_FALSE='#'
+else
+  BUILD_BOOST_WCHAR_TRUE='#'
+  BUILD_BOOST_WCHAR_FALSE=
+fi
+
+
+
 if test "$build_doc" = yes; then
   BUILD_DOC_TRUE=
   BUILD_DOC_FALSE='#'
@@ -29458,6 +29492,13 @@ if test -z "${BUILD_BOOST_THREAD_TRUE}" && test -z "${BUILD_BOOST_THREAD_FALSE}"
   { { echo "$as_me:$LINENO: error: conditional \"BUILD_BOOST_THREAD\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
 echo "$as_me: error: conditional \"BUILD_BOOST_THREAD\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${BUILD_BOOST_WCHAR_TRUE}" && test -z "${BUILD_BOOST_WCHAR_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"BUILD_BOOST_WCHAR\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"BUILD_BOOST_WCHAR\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -30216,6 +30257,8 @@ s,@BUILD_BOOST_SIGNALS_TRUE@,$BUILD_BOOST_SIGNALS_TRUE,;t t
 s,@BUILD_BOOST_SIGNALS_FALSE@,$BUILD_BOOST_SIGNALS_FALSE,;t t
 s,@BUILD_BOOST_THREAD_TRUE@,$BUILD_BOOST_THREAD_TRUE,;t t
 s,@BUILD_BOOST_THREAD_FALSE@,$BUILD_BOOST_THREAD_FALSE,;t t
+s,@BUILD_BOOST_WCHAR_TRUE@,$BUILD_BOOST_WCHAR_TRUE,;t t
+s,@BUILD_BOOST_WCHAR_FALSE@,$BUILD_BOOST_WCHAR_FALSE,;t t
 s,@BUILD_DOC_TRUE@,$BUILD_DOC_TRUE,;t t
 s,@BUILD_DOC_FALSE@,$BUILD_DOC_FALSE,;t t
 s,@BUILD_PDF_TRUE@,$BUILD_PDF_TRUE,;t t
