*** empty log message ***
git-svn-id: svn://localhost:7744/trunk/alps@2365 3665984a-f8b0-4bb5-b30c-cdcaecbe7ced

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -26124,7 +26124,7 @@ rm -f conftest.err conftest.$ac_objext \
       conftest$ac_exeext conftest.$ac_ext
         fi
         if test "$found" = no; then
-          for lapack_libs in '-llapack' '-llapack -lf2c' '-llapack -lg2c'; do
+          for lapack_libs in '-llapack' '-llapack -lf2c' '-llapack -lg2c' 'lapack_ppc64'; do
             LDFLAGS="$lapack_ldflags $LAPACK_LDFLAGS $ac_save_LDFLAGS"
             LIBS="$lapack_libs $LAPACK_LIBS $ac_save_LIBS"
             echo "$as_me:$LINENO: checking for dsyev_ in $lapack_ldflags $lapack_libs" >&5
@@ -26179,9 +26179,9 @@ rm -f conftest.err conftest.$ac_objext \
       conftest$ac_exeext conftest.$ac_ext
             if test "$found" = no; then
               if test -z "$lapack_dir"; then
-                for d in $HOME $HOME/src $prefix /usr/local /usr/local/src; do
-                  if test -d "$d/lib"; then
-                    lapack_ldflags="-L$d/lib"
+                for d in $HOME/lib $HOME/src/lib $prefix/lib /usr/local/lib /usr/local/src/lib /apps/lapack/64/lib /apps/lapack/32/lib; do
+                  if test -d "$d"; then
+                    lapack_ldflags="-L$d"
                     LDFLAGS="$lapack_ldflags $LAPACK_LDFLAGS $ac_save_LDFLAGS"
                     if test "$ac_cv_compiler" = ibm32; then
                       echo "$as_me:$LINENO: checking for dsyev in $lapack_ldflags $lapack_libs" >&5
@@ -26286,6 +26286,58 @@ echo "${ECHO_T}no" >&6
 fi
 rm -f conftest.err conftest.$ac_objext \
       conftest$ac_exeext conftest.$ac_ext
+		    else
+		      if test "$ac_cv_compiler" = ibm; then
+                        echo "$as_me:$LINENO: checking for dsyev in $lapack_ldflags $lapack_libs" >&5
+echo $ECHO_N "checking for dsyev in $lapack_ldflags $lapack_libs... $ECHO_C" >&6
+                        cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+extern "C" char dsyev();
+int
+main ()
+{
+dsyev();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_cxx_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6; found=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+rm -f conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
 		      else
                         echo "$as_me:$LINENO: checking for dsyev_ in $lapack_ldflags $lapack_libs" >&5
 echo $ECHO_N "checking for dsyev_ in $lapack_ldflags $lapack_libs... $ECHO_C" >&6
@@ -26339,6 +26391,7 @@ rm -f conftest.err conftest.$ac_objext \
       conftest$ac_exeext conftest.$ac_ext
 		      fi
 		    fi
+          fi
                     if test "$found" = yes; then
                       break
                     fi
@@ -26361,6 +26414,7 @@ rm -f conftest.err conftest.$ac_objext \
       fi
     fi
   fi
+
 
   LDFLAGS=$ac_save_LDFLAGS
   LIBS=$ac_save_LIBS
