*** empty log message ***
git-svn-id: svn://localhost:7744/trunk/alps@576 3665984a-f8b0-4bb5-b30c-cdcaecbe7ced

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -308,7 +308,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS CURRENT_YEAR COMPILER CPPFLAGS CFLAGS CXXFLAGS CC LDFLAGS ac_ct_CC EXEEXT OBJEXT CXX ac_ct_CXX CPP CXXCPP INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA ALPS_INSTALL AR ARXX LN_S EGREP RANLIB ac_ct_RANLIB BOOST_DIR BOOST_USER_CONFIG_H OBJ_PTHREAD LIB_PTHREAD EXAMPLE_PTHREAD OBJ_BOOST_THREAD LIB_MPI MPI_CPPFLAGS MPI_LDFLAGS MPI_LIBS OBJ_MPI EXAMPLE_MPI LIB_PVM PVM_CPPFLAGS PVM_LDFLAGS PVM_LIBS OBJ_PVM EXAMPLE_PVM HDF5_CPPFLAGS HDF5_LDFLAGS HDF5_LIBS XML_CPPFLAGS XML_LDFLAGS XML_LIBS BASE_CPPFLAGS BASE_LDFLAGS BASE_LIBS LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS CURRENT_YEAR COMPILER CPPFLAGS CFLAGS CXXFLAGS CC LDFLAGS ac_ct_CC EXEEXT OBJEXT CXX ac_ct_CXX CPP CXXCPP INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA ALPS_INSTALL AR ARXX LN_S EGREP RANLIB ac_ct_RANLIB BOOST_DIR OBJ_PTHREAD LIB_PTHREAD EXAMPLE_PTHREAD OBJ_BOOST_THREAD LIB_MPI MPI_CPPFLAGS MPI_LDFLAGS MPI_LIBS OBJ_MPI EXAMPLE_MPI LIB_PVM PVM_CPPFLAGS PVM_LDFLAGS PVM_LIBS OBJ_PVM EXAMPLE_PVM HDF5_CPPFLAGS HDF5_LDFLAGS HDF5_LIBS XML_CPPFLAGS XML_LDFLAGS XML_LIBS OBJ_BOOST_SIGNALS BOOST_USER_CONFIG_H BASE_CPPFLAGS BASE_LDFLAGS BASE_LIBS LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -877,6 +877,9 @@ Optional Packages:
   --with-expat=DIR        use Expat XML parser by James Clark
   --with-xerces=DIR       use Xerces C++ XML parser by Apache Software
                           Foundation
+  --with-boost-all        compile all optional boost libraries
+  --with-boost-signals    compile boost::signals library
+  --with-boost-thread     compile boost::thread library
 
 Some influential environment variables:
   CC          C compiler command
@@ -3878,34 +3881,6 @@ fi
 
 BOOST_DIR="$ac_cv_boost_dir"
 
-# check whether Boost::configure is used or not
-
-# Check whether --enable-boost-config or --disable-boost-config was given.
-if test "${enable_boost_config+set}" = set; then
-  enableval="$enable_boost_config"
-
-  if test "x$enableval" != "xno"; then
-    ac_cv_boost_config=yes
-  fi
-
-
-fi;
-echo "$as_me:$LINENO: checking whether use boost configuration header file" >&5
-echo $ECHO_N "checking whether use boost configuration header file... $ECHO_C" >&6
-test -z "$ac_cv_boost_config" && ac_cv_boost_config=no
-if test "$ac_cv_boost_config" = yes; then
-  ac_cv_boost_config="$includedir/$PACKAGE_NAME/boost-user.hpp"
-  if test -f "$ac_cv_boost_dir/libs/config/configure"; then :; else
-    echo "$as_me:$LINENO: result: " >&5
-echo "${ECHO_T}" >&6
-    { { echo "$as_me:$LINENO: error: boost configure script was not found." >&5
-echo "$as_me: error: boost configure script was not found." >&2;}
-   { (exit 1); exit 1; }; }
-  fi
-fi
-echo "$as_me:$LINENO: result: $ac_cv_boost_config" >&5
-echo "${ECHO_T}$ac_cv_boost_config" >&6
-
 # tools
           ac_config_files="$ac_config_files tool/Makefile"
 
@@ -6021,7 +5996,6 @@ if test "$ac_cv_have_pthread" = yes; then
 #define ALPS_HAVE_PTHREAD 1
 _ACEOF
 
-  OBJ_BOOST_THREAD='$(OBJ_BOOST_THREAD)'
 fi
 
 #
@@ -8404,6 +8378,114 @@ _ACEOF
 
 
 #
+# boost object libraries
+#
+
+# check whether all boost libraries are compiled
+
+# Check whether --with-boost-all or --without-boost-all was given.
+if test "${with_boost_all+set}" = set; then
+  withval="$with_boost_all"
+
+    if test "x$withval" == "xno"; then
+      ac_cv_boost_signals=no
+      ac_cv_boost_thread=no
+    else
+      ac_cv_boost_signals=yes
+      ac_cv_boost_thread=yes
+    fi
+
+
+fi;
+
+# check whether boost::signals is compiled
+
+# Check whether --with-boost-signals or --without-boost-signals was given.
+if test "${with_boost_signals+set}" = set; then
+  withval="$with_boost_signals"
+
+    if test "x$withval" == "xno"; then
+      ac_cv_boost_signals=no
+    else
+      ac_cv_boost_signals=yes
+    fi
+
+
+fi;
+echo "$as_me:$LINENO: checking whether boost::signals is compiled" >&5
+echo $ECHO_N "checking whether boost::signals is compiled... $ECHO_C" >&6
+
+test -z "$ac_cv_boost_signals" && ac_cv_boost_signals=no
+if test "$ac_cv_boost_signals" = yes; then
+  OBJ_BOOST_SIGNALS='$(OBJ_BOOST_SIGNALS)'
+  echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+# check whether boost::thread is compiled
+
+# Check whether --with-boost-thread or --without-boost-thread was given.
+if test "${with_boost_thread+set}" = set; then
+  withval="$with_boost_thread"
+
+    if test "x$withval" == "xno"; then
+      ac_cv_boost_thread=no
+    else
+      ac_cv_boost_thread=yes
+    fi
+
+
+fi;
+echo "$as_me:$LINENO: checking whether boost::thread is compiled" >&5
+echo $ECHO_N "checking whether boost::thread is compiled... $ECHO_C" >&6
+
+test -z "$ac_cv_boost_thread" && ac_cv_boost_thread=no
+if test "$ac_cv_have_pthread" = yes; then
+  if test "$ac_cv_boost_thread" = yes; then
+    OBJ_BOOST_THREAD='$(OBJ_BOOST_THREAD)'
+    echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+  else
+    echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+  fi
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+# check whether Boost::configure is used or not
+
+# Check whether --enable-boost-config or --disable-boost-config was given.
+if test "${enable_boost_config+set}" = set; then
+  enableval="$enable_boost_config"
+
+  if test "x$enableval" != "xno"; then
+    ac_cv_boost_config=yes
+  fi
+
+
+fi;
+echo "$as_me:$LINENO: checking whether use boost configuration header file" >&5
+echo $ECHO_N "checking whether use boost configuration header file... $ECHO_C" >&6
+test -z "$ac_cv_boost_config" && ac_cv_boost_config=no
+if test "$ac_cv_boost_config" = yes; then
+  ac_cv_boost_config="$includedir/$PACKAGE_NAME/boost-user.hpp"
+  if test -f "$ac_cv_boost_dir/libs/config/configure"; then :; else
+    echo "$as_me:$LINENO: result: " >&5
+echo "${ECHO_T}" >&6
+    { { echo "$as_me:$LINENO: error: boost configure script was not found." >&5
+echo "$as_me: error: boost configure script was not found." >&2;}
+   { (exit 1); exit 1; }; }
+  fi
+fi
+echo "$as_me:$LINENO: result: $ac_cv_boost_config" >&5
+echo "${ECHO_T}$ac_cv_boost_config" >&6
+
+#
 # configuring boost
 #
 
@@ -9102,7 +9184,6 @@ s,@EGREP@,$EGREP,;t t
 s,@RANLIB@,$RANLIB,;t t
 s,@ac_ct_RANLIB@,$ac_ct_RANLIB,;t t
 s,@BOOST_DIR@,$BOOST_DIR,;t t
-s,@BOOST_USER_CONFIG_H@,$BOOST_USER_CONFIG_H,;t t
 s,@OBJ_PTHREAD@,$OBJ_PTHREAD,;t t
 s,@LIB_PTHREAD@,$LIB_PTHREAD,;t t
 s,@EXAMPLE_PTHREAD@,$EXAMPLE_PTHREAD,;t t
@@ -9125,6 +9206,8 @@ s,@HDF5_LIBS@,$HDF5_LIBS,;t t
 s,@XML_CPPFLAGS@,$XML_CPPFLAGS,;t t
 s,@XML_LDFLAGS@,$XML_LDFLAGS,;t t
 s,@XML_LIBS@,$XML_LIBS,;t t
+s,@OBJ_BOOST_SIGNALS@,$OBJ_BOOST_SIGNALS,;t t
+s,@BOOST_USER_CONFIG_H@,$BOOST_USER_CONFIG_H,;t t
 s,@BASE_CPPFLAGS@,$BASE_CPPFLAGS,;t t
 s,@BASE_LDFLAGS@,$BASE_LDFLAGS,;t t
 s,@BASE_LIBS@,$BASE_LIBS,;t t
