*** empty log message ***
git-svn-id: svn://localhost:7744/trunk/alps@2284 3665984a-f8b0-4bb5-b30c-cdcaecbe7ced

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -27501,7 +27501,7 @@ echo "${ECHO_T}yes" >&6
 echo "${ECHO_T}$mpi_dir" >&6
       if test -f "$mpi_dir/include/mpi.h"; then :; else
         { { echo "$as_me:$LINENO: error: $mpi_dir/include/mpi.h not found" >&5
-echo "$as_me: error: $mpi_dir/include/mpih.h not found" >&2;}
+echo "$as_me: error: $mpi_dir/include/mpi.h not found" >&2;}
    { (exit 1); exit 1; }; }
       fi
       if test -d "$mpi_dir/lib"; then :; else
