*** empty log message ***
git-svn-id: svn://localhost:7744/trunk/alps@1770 3665984a-f8b0-4bb5-b30c-cdcaecbe7ced

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -463,7 +463,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT LIB_VERSION_INFO ALPS_FULL_TRUE ALPS_FULL_FALSE ALPS_LIGHT_TRUE ALPS_LIGHT_FALSE docdir SRC_DIR ALPS_XML_DIR build build_cpu build_vendor build_os host host_cpu host_vendor host_os COMPILER CPPFLAGS CFLAGS CXXFLAGS CC LDFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CXX ac_ct_CXX CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE CPP CXXCPP EGREP LN_S ECHO AR ac_ct_AR RANLIB ac_ct_RANLIB F77 FFLAGS ac_ct_F77 LIBTOOL BOOST_CPPFLAGS BOOST_LDFLAGS BOOST_LIBS BOOST_INCDIR BOOST_DIR BOOST_SRCDIR BUILD_BOOST_TRUE BUILD_BOOST_FALSE BOOST_1_32_TRUE BOOST_1_32_FALSE BOOST_1_33_TRUE BOOST_1_33_FALSE OBJ_PTHREAD LIB_PTHREAD EXAMPLE_PTHREAD LIB_MPI MPI_CPPFLAGS MPI_LDFLAGS MPI_LIBS OBJ_MPI EXAMPLE_MPI HAVE_MPI_TRUE HAVE_MPI_FALSE LIB_PVM PVM_CPPFLAGS PVM_LDFLAGS PVM_LIBS OBJ_PVM EXAMPLE_PVM HAVE_PVM_TRUE HAVE_PVM_FALSE LAPACK_CPPFLAGS LAPACK_LDFLAGS LAPACK_LIBS HDF5_CPPFLAGS HDF5_LDFLAGS HDF5_LIBS XML_CPPFLAGS XML_LDFLAGS XML_LIBS BUILD_BOOST_SIGNALS_TRUE BUILD_BOOST_SIGNALS_FALSE BUILD_BOOST_THREAD_TRUE BUILD_BOOST_THREAD_FALSE BOOST_USER_CONFIG_H ac_cv_prog_doxygen DOXYGEN ac_cv_prog_xsltproc XSLTPROC ac_cv_prog_java JAVA DOCBOOK_DTD_DIR DOCBOOK_XSL_DIR FOP_DIR BUILD_DOC_TRUE BUILD_DOC_FALSE BUILD_PDF_TRUE BUILD_PDF_FALSE BASE_CPPFLAGS BASE_LDFLAGS BASE_LIBS BUILD_LIBHEAP_TRUE BUILD_LIBHEAP_FALSE LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT LIB_VERSION_INFO ALPS_FULL_TRUE ALPS_FULL_FALSE ALPS_LIGHT_TRUE ALPS_LIGHT_FALSE docdir SRC_DIR ALPS_XML_DIR build build_cpu build_vendor build_os host host_cpu host_vendor host_os COMPILER CPPFLAGS CFLAGS CXXFLAGS CC LDFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CXX ac_ct_CXX CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE CPP CXXCPP EGREP LN_S ECHO AR ac_ct_AR RANLIB ac_ct_RANLIB F77 FFLAGS ac_ct_F77 LIBTOOL BOOST_CPPFLAGS BOOST_LDFLAGS BOOST_LIBS BOOST_INCDIR BOOST_CVS_TRUE BOOST_CVS_FALSE BOOST_1_33_TRUE BOOST_1_33_FALSE BOOST_1_32_TRUE BOOST_1_32_FALSE BOOST_DIR BOOST_SRCDIR BUILD_BOOST_TRUE BUILD_BOOST_FALSE OBJ_PTHREAD LIB_PTHREAD EXAMPLE_PTHREAD LIB_MPI MPI_CPPFLAGS MPI_LDFLAGS MPI_LIBS OBJ_MPI EXAMPLE_MPI HAVE_MPI_TRUE HAVE_MPI_FALSE LIB_PVM PVM_CPPFLAGS PVM_LDFLAGS PVM_LIBS OBJ_PVM EXAMPLE_PVM HAVE_PVM_TRUE HAVE_PVM_FALSE LAPACK_CPPFLAGS LAPACK_LDFLAGS LAPACK_LIBS HDF5_CPPFLAGS HDF5_LDFLAGS HDF5_LIBS XML_CPPFLAGS XML_LDFLAGS XML_LIBS BUILD_BOOST_SIGNALS_TRUE BUILD_BOOST_SIGNALS_FALSE BUILD_BOOST_THREAD_TRUE BUILD_BOOST_THREAD_FALSE BOOST_USER_CONFIG_H ac_cv_prog_doxygen DOXYGEN ac_cv_prog_xsltproc XSLTPROC ac_cv_prog_java JAVA DOCBOOK_DTD_DIR DOCBOOK_XSL_DIR FOP_DIR BUILD_DOC_TRUE BUILD_DOC_FALSE BUILD_PDF_TRUE BUILD_PDF_FALSE BASE_CPPFLAGS BASE_LDFLAGS BASE_LIBS BUILD_LIBHEAP_TRUE BUILD_LIBHEAP_FALSE LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -22193,6 +22193,203 @@ echo "$as_me: error: Boost include files not found" >&2;}
 fi
 
 
+echo "$as_me:$LINENO: checking for Boost version" >&5
+echo $ECHO_N "checking for Boost version... $ECHO_C" >&6
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <boost/foreach.hpp>
+int
+main ()
+{
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_cxx_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_boost_version=cvs
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+fi
+rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
+if test -z "$ac_cv_boost_version"; then
+  cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <boost/version.hpp>
+#if BOOST_VERSION != 103300
+#error
+#endif
+int
+main ()
+{
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_cxx_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_boost_version=1_33
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+fi
+rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
+fi
+if test -z "$ac_cv_boost_version"; then
+  cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <boost/version.hpp>
+#if BOOST_VERSION != 103200
+#error
+#endif
+int
+main ()
+{
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_cxx_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_boost_version=1_32
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+fi
+rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
+fi
+case "x$ac_cv_boost_version" in
+  xcvs )
+    echo "$as_me:$LINENO: result: CVS" >&5
+echo "${ECHO_T}CVS" >&6
+    ;;
+  x1_33 )
+    echo "$as_me:$LINENO: result: 1.33.0" >&5
+echo "${ECHO_T}1.33.0" >&6
+    ;;
+  x1_32 )
+    echo "$as_me:$LINENO: result: 1.32.0" >&5
+echo "${ECHO_T}1.32.0" >&6
+    ;;
+  * )
+    echo "$as_me:$LINENO: result: unknown" >&5
+echo "${ECHO_T}unknown" >&6
+    { { echo "$as_me:$LINENO: error: Boost library is too old" >&5
+echo "$as_me: error: Boost library is too old" >&2;}
+   { (exit 1); exit 1; }; }
+    ;;
+esac
+
+
+if test "$ac_cv_boost_version" = cvs; then
+  BOOST_CVS_TRUE=
+  BOOST_CVS_FALSE='#'
+else
+  BOOST_CVS_TRUE='#'
+  BOOST_CVS_FALSE=
+fi
+
+
+
+if test "$ac_cv_boost_version" = 1_33; then
+  BOOST_1_33_TRUE=
+  BOOST_1_33_FALSE='#'
+else
+  BOOST_1_33_TRUE='#'
+  BOOST_1_33_FALSE=
+fi
+
+
+
+if test "$ac_cv_boost_version" = 1_32; then
+  BOOST_1_32_TRUE=
+  BOOST_1_32_FALSE='#'
+else
+  BOOST_1_32_TRUE='#'
+  BOOST_1_32_FALSE=
+fi
+
+
+
 if test "$ac_cv_use_precompiled_boost" = no; then :; else
 
   echo "$as_me:$LINENO: checking for Boost toolset abbreviation" >&5
@@ -22573,17 +22770,6 @@ echo "$as_me: error: Boost source files not found" >&2;}
    { (exit 1); exit 1; }; }
     fi
   fi
-  echo "$as_me:$LINENO: checking for Boost version" >&5
-echo $ECHO_N "checking for Boost version... $ECHO_C" >&6
-  if test -f "$BOOST_SRCDIR/regex/src/c_regex_traits_common.cpp"; then
-     echo "$as_me:$LINENO: result: 1.32" >&5
-echo "${ECHO_T}1.32" >&6
-     ac_cv_boost_version=1_32
-  else
-     echo "$as_me:$LINENO: result: 1.33" >&5
-echo "${ECHO_T}1.33" >&6
-     ac_cv_boost_version=1_33
-  fi
 fi
 
 
@@ -22593,26 +22779,6 @@ if test "$ac_cv_use_precompiled_boost" != yes; then
 else
   BUILD_BOOST_TRUE='#'
   BUILD_BOOST_FALSE=
-fi
-
-
-
-if test "$ac_cv_boost_version" = 1_32; then
-  BOOST_1_32_TRUE=
-  BOOST_1_32_FALSE='#'
-else
-  BOOST_1_32_TRUE='#'
-  BOOST_1_32_FALSE=
-fi
-
-
-
-if test "$ac_cv_boost_version" = 1_33; then
-  BOOST_1_33_TRUE=
-  BOOST_1_33_FALSE='#'
-else
-  BOOST_1_33_TRUE='#'
-  BOOST_1_33_FALSE=
 fi
 
 
@@ -29912,7 +30078,7 @@ echo "${ECHO_T}$fop_dir" >&6
 
 test "$ac_cv_have_fop" = yes && FOP_DIR="$ac_cv_fop_dir"
 
-if test -n "$BOOST_SRCDIR" && test -n "$ac_cv_prog_doxygen" && test -n "$ac_cv_prog_xsltproc" && test "$ac_cv_have_docbook_dtd" = yes && test "$ac_cv_have_docbook_xsl" = yes; then
+if test -n "$BOOST_SRCDIR" && test "$ac_cv_boost_version" != 1_32 && test -n "$ac_cv_prog_doxygen" && test -n "$ac_cv_prog_xsltproc" && test "$ac_cv_have_docbook_dtd" = yes && test "$ac_cv_have_docbook_xsl" = yes; then
   build_doc=yes
   if test "$ac_cv_have_fop" = yes; then
     build_pdf=yes
@@ -30186,10 +30352,17 @@ echo "$as_me: error: conditional \"am__fastdepCXX\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
-if test -z "${BUILD_BOOST_TRUE}" && test -z "${BUILD_BOOST_FALSE}"; then
-  { { echo "$as_me:$LINENO: error: conditional \"BUILD_BOOST\" was never defined.
+if test -z "${BOOST_CVS_TRUE}" && test -z "${BOOST_CVS_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"BOOST_CVS\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
-echo "$as_me: error: conditional \"BUILD_BOOST\" was never defined.
+echo "$as_me: error: conditional \"BOOST_CVS\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${BOOST_1_33_TRUE}" && test -z "${BOOST_1_33_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"BOOST_1_33\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"BOOST_1_33\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -30200,10 +30373,10 @@ echo "$as_me: error: conditional \"BOOST_1_32\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
-if test -z "${BOOST_1_33_TRUE}" && test -z "${BOOST_1_33_FALSE}"; then
-  { { echo "$as_me:$LINENO: error: conditional \"BOOST_1_33\" was never defined.
+if test -z "${BUILD_BOOST_TRUE}" && test -z "${BUILD_BOOST_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"BUILD_BOOST\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
-echo "$as_me: error: conditional \"BOOST_1_33\" was never defined.
+echo "$as_me: error: conditional \"BUILD_BOOST\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -30922,14 +31095,16 @@ s,@BOOST_CPPFLAGS@,$BOOST_CPPFLAGS,;t t
 s,@BOOST_LDFLAGS@,$BOOST_LDFLAGS,;t t
 s,@BOOST_LIBS@,$BOOST_LIBS,;t t
 s,@BOOST_INCDIR@,$BOOST_INCDIR,;t t
+s,@BOOST_CVS_TRUE@,$BOOST_CVS_TRUE,;t t
+s,@BOOST_CVS_FALSE@,$BOOST_CVS_FALSE,;t t
+s,@BOOST_1_33_TRUE@,$BOOST_1_33_TRUE,;t t
+s,@BOOST_1_33_FALSE@,$BOOST_1_33_FALSE,;t t
+s,@BOOST_1_32_TRUE@,$BOOST_1_32_TRUE,;t t
+s,@BOOST_1_32_FALSE@,$BOOST_1_32_FALSE,;t t
 s,@BOOST_DIR@,$BOOST_DIR,;t t
 s,@BOOST_SRCDIR@,$BOOST_SRCDIR,;t t
 s,@BUILD_BOOST_TRUE@,$BUILD_BOOST_TRUE,;t t
 s,@BUILD_BOOST_FALSE@,$BUILD_BOOST_FALSE,;t t
-s,@BOOST_1_32_TRUE@,$BOOST_1_32_TRUE,;t t
-s,@BOOST_1_32_FALSE@,$BOOST_1_32_FALSE,;t t
-s,@BOOST_1_33_TRUE@,$BOOST_1_33_TRUE,;t t
-s,@BOOST_1_33_FALSE@,$BOOST_1_33_FALSE,;t t
 s,@OBJ_PTHREAD@,$OBJ_PTHREAD,;t t
 s,@LIB_PTHREAD@,$LIB_PTHREAD,;t t
 s,@EXAMPLE_PTHREAD@,$EXAMPLE_PTHREAD,;t t
