git-svn-id: svn://localhost:7744/trunk/alps@2756 3665984a-f8b0-4bb5-b30c-cdcaecbe7ced

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -463,7 +463,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT LIB_VERSION_INFO docdir SRC_DIR ALPS_XML_DIR build build_cpu build_vendor build_os host host_cpu host_vendor host_os COMPILER CPPFLAGS CFLAGS CXXFLAGS CC LDFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CXX ac_ct_CXX CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE CPP CXXCPP EGREP LN_S ECHO AR ac_ct_AR RANLIB ac_ct_RANLIB F77 FFLAGS ac_ct_F77 LIBTOOL BOOST_CPPFLAGS BOOST_LDFLAGS BOOST_LIBS BOOST_INCDIR BOOST_DIR BOOST_SRCDIR OBJ_PTHREAD LIB_PTHREAD EXAMPLE_PTHREAD HDF5_CPPFLAGS HDF5_LDFLAGS HDF5_LIBS LAPACK_CPPFLAGS LAPACK_LDFLAGS LAPACK_LIBS SQLITE_CPPFLAGS SQLITE_LDFLAGS SQLITE_LIBS XML_CPPFLAGS XML_LDFLAGS XML_LIBS LIB_MPI MPI_CPPFLAGS MPI_LDFLAGS MPI_LIBS OBJ_MPI EXAMPLE_MPI BOOST_USER_CONFIG_H ac_cv_prog_doxygen DOXYGEN ac_cv_prog_xsltproc XSLTPROC ac_cv_prog_java JAVA DOCBOOK_DTD_DIR DOCBOOK_XSL_DIR FOP_DIR FOP_BIN FOP_OPTS JAVA_OPTS BASE_CPPFLAGS BASE_LDFLAGS BASE_LIBS abs_top_srcdir ALPS_FULL_TRUE ALPS_FULL_FALSE ALPS_LIGHT_TRUE ALPS_LIGHT_FALSE BOOST_1_32_TRUE BOOST_1_32_FALSE BOOST_1_33_TRUE BOOST_1_33_FALSE BOOST_1_34_TRUE BOOST_1_34_FALSE BOOST_CVS_TRUE BOOST_CVS_FALSE BUILD_BOOST_TRUE BUILD_BOOST_FALSE BUILD_BOOST_SIGNALS_TRUE BUILD_BOOST_SIGNALS_FALSE BUILD_BOOST_THREAD_TRUE BUILD_BOOST_THREAD_FALSE BUILD_BOOST_WCHAR_TRUE BUILD_BOOST_WCHAR_FALSE BUILD_DOC_TRUE BUILD_DOC_FALSE BUILD_PDF_TRUE BUILD_PDF_FALSE BUILD_LIBHEAP_TRUE BUILD_LIBHEAP_FALSE BUILD_ARCHIVE_TRUE BUILD_ARCHIVE_FALSE HAVE_MPI_TRUE HAVE_MPI_FALSE LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT LIB_VERSION_INFO docdir SRC_DIR ALPS_XML_DIR build build_cpu build_vendor build_os host host_cpu host_vendor host_os COMPILER CPPFLAGS CFLAGS CXXFLAGS CC LDFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CXX ac_ct_CXX CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE CPP CXXCPP EGREP LN_S ECHO AR ac_ct_AR RANLIB ac_ct_RANLIB F77 FFLAGS ac_ct_F77 LIBTOOL BOOST_CPPFLAGS BOOST_LDFLAGS BOOST_LIBS BOOST_INCDIR BOOST_DIR BOOST_SRCDIR OBJ_PTHREAD LIB_PTHREAD EXAMPLE_PTHREAD HDF5_CPPFLAGS HDF5_LDFLAGS HDF5_LIBS LAPACK_CPPFLAGS LAPACK_LDFLAGS LAPACK_LIBS SQLITE_CPPFLAGS SQLITE_LDFLAGS SQLITE_LIBS XML_CPPFLAGS XML_LDFLAGS XML_LIBS LIB_MPI MPI_CPPFLAGS MPI_LDFLAGS MPI_LIBS OBJ_MPI EXAMPLE_MPI BOOST_USER_CONFIG_H ac_cv_prog_doxygen DOXYGEN ac_cv_prog_xsltproc XSLTPROC ac_cv_prog_java JAVA DOCBOOK_DTD_DIR DOCBOOK_XSL_DIR FOP_DIR FOP_BIN FOP_OPTS JAVA_OPTS BASE_CPPFLAGS BASE_LDFLAGS BASE_LIBS abs_top_srcdir ALPS_FULL_TRUE ALPS_FULL_FALSE ALPS_LIGHT_TRUE ALPS_LIGHT_FALSE BOOST_1_32_TRUE BOOST_1_32_FALSE BOOST_1_33_TRUE BOOST_1_33_FALSE BOOST_1_34_TRUE BOOST_1_34_FALSE BOOST_1_35_TRUE BOOST_1_35_FALSE BOOST_SVN_TRUE BOOST_SVN_FALSE BUILD_BOOST_TRUE BUILD_BOOST_FALSE BUILD_BOOST_SIGNALS_TRUE BUILD_BOOST_SIGNALS_FALSE BUILD_BOOST_THREAD_TRUE BUILD_BOOST_THREAD_FALSE BUILD_BOOST_WCHAR_TRUE BUILD_BOOST_WCHAR_FALSE BUILD_DOC_TRUE BUILD_DOC_FALSE BUILD_PDF_TRUE BUILD_PDF_FALSE BUILD_LIBHEAP_TRUE BUILD_LIBHEAP_FALSE BUILD_ARCHIVE_TRUE BUILD_ARCHIVE_FALSE HAVE_MPI_TRUE HAVE_MPI_FALSE LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -21319,7 +21319,7 @@ fi;
 boost_dir_s=
 
 for d in $HOME $HOME/src $prefix $prefix/src /usr/local /usr/local/src; do
-  for b in boost boost_1_34_1 boost_1_34_0 boost_1_33_1 boost_1_33_0 boost_1_32_0; do
+  for b in boost boost_1_35_0 boost_1_34_1 boost_1_34_0 boost_1_33_1 boost_1_33_0 boost_1_32_0; do
     if test -f "$d/$b/boost/config.hpp"; then
       if test -f "$d/$b/libs/filesystem/src/exception.cpp"; then
         boost_dir_s="$d/$b"
@@ -21484,6 +21484,54 @@ cat confdefs.h >>conftest.$ac_ext
 cat >>conftest.$ac_ext <<_ACEOF
 /* end confdefs.h.  */
 #include <boost/version.hpp>
+#if BOOST_VERSION < 103600
+#error
+#endif
+int
+main ()
+{
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_cxx_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_boost_version=svn
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+fi
+rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
+if test -z "$ac_cv_boost_version"; then
+  cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <boost/version.hpp>
 #if BOOST_VERSION < 103500
 #error
 #endif
@@ -21517,13 +21565,14 @@ if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   ac_status=$?
   echo "$as_me:$LINENO: \$? = $ac_status" >&5
   (exit $ac_status); }; }; then
-  ac_cv_boost_version=cvs
+  ac_cv_boost_version=1_35
 else
   echo "$as_me: failed program was:" >&5
 sed 's/^/| /' conftest.$ac_ext >&5
 
 fi
 rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
+fi
 if test -z "$ac_cv_boost_version"; then
   cat >conftest.$ac_ext <<_ACEOF
 /* confdefs.h.  */
@@ -21672,9 +21721,13 @@ fi
 rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
 fi
 case "x$ac_cv_boost_version" in
-  xcvs )
-    echo "$as_me:$LINENO: result: CVS" >&5
-echo "${ECHO_T}CVS" >&6
+  xsvn )
+    echo "$as_me:$LINENO: result: SVN" >&5
+echo "${ECHO_T}SVN" >&6
+    ;;
+  x1_35 )
+    echo "$as_me:$LINENO: result: 1.35" >&5
+echo "${ECHO_T}1.35" >&6
     ;;
   x1_34 )
     echo "$as_me:$LINENO: result: 1.34" >&5
@@ -29498,12 +29551,22 @@ fi
 
 
 
-if test "$ac_cv_boost_version" = cvs; then
-  BOOST_CVS_TRUE=
-  BOOST_CVS_FALSE='#'
+if test "$ac_cv_boost_version" = 1_35; then
+  BOOST_1_35_TRUE=
+  BOOST_1_35_FALSE='#'
 else
-  BOOST_CVS_TRUE='#'
-  BOOST_CVS_FALSE=
+  BOOST_1_35_TRUE='#'
+  BOOST_1_35_FALSE=
+fi
+
+
+
+if test "$ac_cv_boost_version" = svn; then
+  BOOST_SVN_TRUE=
+  BOOST_SVN_FALSE='#'
+else
+  BOOST_SVN_TRUE='#'
+  BOOST_SVN_FALSE=
 fi
 
 
@@ -29639,7 +29702,7 @@ _ACEOF
 
             ac_config_headers="$ac_config_headers src/boost/sr_utf8_codecvt_facet.cpp"
 
-  if test "$ac_cv_boost_version" = 1_34 || test "$ac_cv_boost_version" = cvs; then
+  if test "$ac_cv_boost_version" = 1_34 || test "$ac_cv_boost_version" = 1_35 || test "$ac_cv_boost_version" = svn; then
     cat >>confdefs.h <<_ACEOF
 #define FS_UTF8_CODECVT_FACET_CPP "$BOOST_SRCDIR/filesystem/src/utf8_codecvt_facet.cpp"
 _ACEOF
@@ -29820,10 +29883,17 @@ echo "$as_me: error: conditional \"BOOST_1_34\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
-if test -z "${BOOST_CVS_TRUE}" && test -z "${BOOST_CVS_FALSE}"; then
-  { { echo "$as_me:$LINENO: error: conditional \"BOOST_CVS\" was never defined.
+if test -z "${BOOST_1_35_TRUE}" && test -z "${BOOST_1_35_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"BOOST_1_35\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
-echo "$as_me: error: conditional \"BOOST_CVS\" was never defined.
+echo "$as_me: error: conditional \"BOOST_1_35\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${BOOST_SVN_TRUE}" && test -z "${BOOST_SVN_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"BOOST_SVN\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"BOOST_SVN\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -30602,8 +30672,10 @@ s,@BOOST_1_33_TRUE@,$BOOST_1_33_TRUE,;t t
 s,@BOOST_1_33_FALSE@,$BOOST_1_33_FALSE,;t t
 s,@BOOST_1_34_TRUE@,$BOOST_1_34_TRUE,;t t
 s,@BOOST_1_34_FALSE@,$BOOST_1_34_FALSE,;t t
-s,@BOOST_CVS_TRUE@,$BOOST_CVS_TRUE,;t t
-s,@BOOST_CVS_FALSE@,$BOOST_CVS_FALSE,;t t
+s,@BOOST_1_35_TRUE@,$BOOST_1_35_TRUE,;t t
+s,@BOOST_1_35_FALSE@,$BOOST_1_35_FALSE,;t t
+s,@BOOST_SVN_TRUE@,$BOOST_SVN_TRUE,;t t
+s,@BOOST_SVN_FALSE@,$BOOST_SVN_FALSE,;t t
 s,@BUILD_BOOST_TRUE@,$BUILD_BOOST_TRUE,;t t
 s,@BUILD_BOOST_FALSE@,$BUILD_BOOST_FALSE,;t t
 s,@BUILD_BOOST_SIGNALS_TRUE@,$BUILD_BOOST_SIGNALS_TRUE,;t t
