*** empty log message ***
git-svn-id: svn://localhost:7744/trunk/alps@1828 3665984a-f8b0-4bb5-b30c-cdcaecbe7ced

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -22231,6 +22231,55 @@ cat confdefs.h >>conftest.$ac_ext
 cat >>conftest.$ac_ext <<_ACEOF
 /* end confdefs.h.  */
 #include <boost/version.hpp>
+#if BOOST_VERSION != 103301
+#error
+#endif
+int
+main ()
+{
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_cxx_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_boost_version=1_33_1
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+fi
+rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
+fi
+if test -z "$ac_cv_boost_version"; then
+  cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <boost/version.hpp>
 #if BOOST_VERSION != 103300
 #error
 #endif
@@ -22325,6 +22374,10 @@ case "x$ac_cv_boost_version" in
   xcvs )
     echo "$as_me:$LINENO: result: CVS" >&5
 echo "${ECHO_T}CVS" >&6
+    ;;
+  x1_33_1 )
+    echo "$as_me:$LINENO: result: 1.33.1" >&5
+echo "${ECHO_T}1.33.1" >&6
     ;;
   x1_33 )
     echo "$as_me:$LINENO: result: 1.33.0" >&5
@@ -30360,7 +30413,7 @@ fi
 
 
 
-if test "$ac_cv_boost_version" = 1_33; then
+if test "$ac_cv_boost_version" = 1_33 || test "$ac_cv_boost_version" = 1_33_1; then
   BOOST_1_33_TRUE=
   BOOST_1_33_FALSE='#'
 else
