*** empty log message ***
git-svn-id: svn://localhost:7744/trunk/alps@2151 3665984a-f8b0-4bb5-b30c-cdcaecbe7ced

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -463,7 +463,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT LIB_VERSION_INFO docdir SRC_DIR ALPS_XML_DIR build build_cpu build_vendor build_os host host_cpu host_vendor host_os COMPILER CPPFLAGS CFLAGS CXXFLAGS CC LDFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CXX ac_ct_CXX CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE CPP CXXCPP EGREP LN_S ECHO AR ac_ct_AR RANLIB ac_ct_RANLIB F77 FFLAGS ac_ct_F77 LIBTOOL BOOST_CPPFLAGS BOOST_LDFLAGS BOOST_LIBS BOOST_INCDIR BOOST_DIR BOOST_SRCDIR OBJ_PTHREAD LIB_PTHREAD EXAMPLE_PTHREAD HDF5_CPPFLAGS HDF5_LDFLAGS HDF5_LIBS LAPACK_CPPFLAGS LAPACK_LDFLAGS LAPACK_LIBS SQLITE_CPPFLAGS SQLITE_LDFLAGS SQLITE_LIBS XML_CPPFLAGS XML_LDFLAGS XML_LIBS LIB_MPI MPI_CPPFLAGS MPI_LDFLAGS MPI_LIBS OBJ_MPI EXAMPLE_MPI BOOST_USER_CONFIG_H ac_cv_prog_doxygen DOXYGEN ac_cv_prog_xsltproc XSLTPROC ac_cv_prog_java JAVA DOCBOOK_DTD_DIR DOCBOOK_XSL_DIR FOP_DIR FOP_BIN FOP_OPTS BASE_CPPFLAGS BASE_LDFLAGS BASE_LIBS abs_top_srcdir ALPS_FULL_TRUE ALPS_FULL_FALSE ALPS_LIGHT_TRUE ALPS_LIGHT_FALSE BOOST_1_32_TRUE BOOST_1_32_FALSE BOOST_1_33_TRUE BOOST_1_33_FALSE BOOST_CVS_TRUE BOOST_CVS_FALSE BUILD_BOOST_TRUE BUILD_BOOST_FALSE BUILD_BOOST_SIGNALS_TRUE BUILD_BOOST_SIGNALS_FALSE BUILD_BOOST_THREAD_TRUE BUILD_BOOST_THREAD_FALSE BUILD_DOC_TRUE BUILD_DOC_FALSE BUILD_PDF_TRUE BUILD_PDF_FALSE BUILD_LIBHEAP_TRUE BUILD_LIBHEAP_FALSE BUILD_ARCHIVE_TRUE BUILD_ARCHIVE_FALSE HAVE_MPI_TRUE HAVE_MPI_FALSE LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT LIB_VERSION_INFO docdir SRC_DIR ALPS_XML_DIR build build_cpu build_vendor build_os host host_cpu host_vendor host_os COMPILER CPPFLAGS CFLAGS CXXFLAGS CC LDFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CXX ac_ct_CXX CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE CPP CXXCPP EGREP LN_S ECHO AR ac_ct_AR RANLIB ac_ct_RANLIB F77 FFLAGS ac_ct_F77 LIBTOOL BOOST_CPPFLAGS BOOST_LDFLAGS BOOST_LIBS BOOST_INCDIR BOOST_DIR BOOST_SRCDIR OBJ_PTHREAD LIB_PTHREAD EXAMPLE_PTHREAD HDF5_CPPFLAGS HDF5_LDFLAGS HDF5_LIBS LAPACK_CPPFLAGS LAPACK_LDFLAGS LAPACK_LIBS SQLITE_CPPFLAGS SQLITE_LDFLAGS SQLITE_LIBS XML_CPPFLAGS XML_LDFLAGS XML_LIBS LIB_MPI MPI_CPPFLAGS MPI_LDFLAGS MPI_LIBS OBJ_MPI EXAMPLE_MPI BOOST_USER_CONFIG_H ac_cv_prog_doxygen DOXYGEN ac_cv_prog_xsltproc XSLTPROC ac_cv_prog_java JAVA DOCBOOK_DTD_DIR DOCBOOK_XSL_DIR FOP_DIR FOP_BIN FOP_OPTS BASE_CPPFLAGS BASE_LDFLAGS BASE_LIBS abs_top_srcdir ALPS_FULL_TRUE ALPS_FULL_FALSE ALPS_LIGHT_TRUE ALPS_LIGHT_FALSE BOOST_1_32_TRUE BOOST_1_32_FALSE BOOST_1_33_TRUE BOOST_1_33_FALSE BOOST_1_34_TRUE BOOST_1_34_FALSE BOOST_CVS_TRUE BOOST_CVS_FALSE BUILD_BOOST_TRUE BUILD_BOOST_FALSE BUILD_BOOST_SIGNALS_TRUE BUILD_BOOST_SIGNALS_FALSE BUILD_BOOST_THREAD_TRUE BUILD_BOOST_THREAD_FALSE BUILD_DOC_TRUE BUILD_DOC_FALSE BUILD_PDF_TRUE BUILD_PDF_FALSE BUILD_LIBHEAP_TRUE BUILD_LIBHEAP_FALSE BUILD_ARCHIVE_TRUE BUILD_ARCHIVE_FALSE HAVE_MPI_TRUE HAVE_MPI_FALSE LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -20935,7 +20935,7 @@ fi;
 boost_dir_s=
 
 for d in $HOME $HOME/src $prefix $prefix/src /usr/local /usr/local/src; do
-  for b in boost boost_1_33_1 boost_1_33_0 boost_1_32_0; do
+  for b in boost boost_1_34_0 boost_1_33_1 boost_1_33_0 boost_1_32_0; do
     if test -f "$d/$b/boost/config.hpp"; then
       if test -f "$d/$b/libs/filesystem/src/exception.cpp"; then
         boost_dir_s="$d/$b"
@@ -21093,13 +21093,16 @@ fi
 
 echo "$as_me:$LINENO: checking for Boost version" >&5
 echo $ECHO_N "checking for Boost version... $ECHO_C" >&6
-cat >conftest.$ac_ext <<_ACEOF
+  cat >conftest.$ac_ext <<_ACEOF
 /* confdefs.h.  */
 _ACEOF
 cat confdefs.h >>conftest.$ac_ext
 cat >>conftest.$ac_ext <<_ACEOF
 /* end confdefs.h.  */
-#include <boost/foreach.hpp>
+#include <boost/version.hpp>
+#if BOOST_VERSION < 103500
+#error
+#endif
 int
 main ()
 {
@@ -21145,7 +21148,7 @@ cat confdefs.h >>conftest.$ac_ext
 cat >>conftest.$ac_ext <<_ACEOF
 /* end confdefs.h.  */
 #include <boost/version.hpp>
-#if BOOST_VERSION != 103301
+#if BOOST_VERSION < 103400
 #error
 #endif
 int
@@ -21178,7 +21181,7 @@ if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   ac_status=$?
   echo "$as_me:$LINENO: \$? = $ac_status" >&5
   (exit $ac_status); }; }; then
-  ac_cv_boost_version=1_33_1
+  ac_cv_boost_version=1_34
 else
   echo "$as_me: failed program was:" >&5
 sed 's/^/| /' conftest.$ac_ext >&5
@@ -21194,7 +21197,7 @@ cat confdefs.h >>conftest.$ac_ext
 cat >>conftest.$ac_ext <<_ACEOF
 /* end confdefs.h.  */
 #include <boost/version.hpp>
-#if BOOST_VERSION != 103300
+#if BOOST_VERSION < 103300
 #error
 #endif
 int
@@ -21243,7 +21246,7 @@ cat confdefs.h >>conftest.$ac_ext
 cat >>conftest.$ac_ext <<_ACEOF
 /* end confdefs.h.  */
 #include <boost/version.hpp>
-#if BOOST_VERSION != 103200
+#if BOOST_VERSION < 103200
 #error
 #endif
 int
@@ -21289,17 +21292,17 @@ case "x$ac_cv_boost_version" in
     echo "$as_me:$LINENO: result: CVS" >&5
 echo "${ECHO_T}CVS" >&6
     ;;
-  x1_33_1 )
-    echo "$as_me:$LINENO: result: 1.33.1" >&5
-echo "${ECHO_T}1.33.1" >&6
+  x1_34 )
+    echo "$as_me:$LINENO: result: 1.34" >&5
+echo "${ECHO_T}1.34" >&6
     ;;
   x1_33 )
-    echo "$as_me:$LINENO: result: 1.33.0" >&5
-echo "${ECHO_T}1.33.0" >&6
+    echo "$as_me:$LINENO: result: 1.33" >&5
+echo "${ECHO_T}1.33" >&6
     ;;
   x1_32 )
-    echo "$as_me:$LINENO: result: 1.32.0" >&5
-echo "${ECHO_T}1.32.0" >&6
+    echo "$as_me:$LINENO: result: 1.32" >&5
+echo "${ECHO_T}1.32" >&6
     ;;
   * )
     echo "$as_me:$LINENO: result: unknown" >&5
@@ -28727,12 +28730,22 @@ fi
 
 
 
-if test "$ac_cv_boost_version" = 1_33 || test "$ac_cv_boost_version" = 1_33_1; then
+if test "$ac_cv_boost_version" = 1_33; then
   BOOST_1_33_TRUE=
   BOOST_1_33_FALSE='#'
 else
   BOOST_1_33_TRUE='#'
   BOOST_1_33_FALSE=
+fi
+
+
+
+if test "$ac_cv_boost_version" = 1_34; then
+  BOOST_1_34_TRUE=
+  BOOST_1_34_FALSE='#'
+else
+  BOOST_1_34_TRUE='#'
+  BOOST_1_34_FALSE=
 fi
 
 
@@ -29041,6 +29054,13 @@ if test -z "${BOOST_1_33_TRUE}" && test -z "${BOOST_1_33_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"BOOST_1_33\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
 echo "$as_me: error: conditional \"BOOST_1_33\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${BOOST_1_34_TRUE}" && test -z "${BOOST_1_34_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"BOOST_1_34\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"BOOST_1_34\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -29816,6 +29836,8 @@ s,@BOOST_1_32_TRUE@,$BOOST_1_32_TRUE,;t t
 s,@BOOST_1_32_FALSE@,$BOOST_1_32_FALSE,;t t
 s,@BOOST_1_33_TRUE@,$BOOST_1_33_TRUE,;t t
 s,@BOOST_1_33_FALSE@,$BOOST_1_33_FALSE,;t t
+s,@BOOST_1_34_TRUE@,$BOOST_1_34_TRUE,;t t
+s,@BOOST_1_34_FALSE@,$BOOST_1_34_FALSE,;t t
 s,@BOOST_CVS_TRUE@,$BOOST_CVS_TRUE,;t t
 s,@BOOST_CVS_FALSE@,$BOOST_CVS_FALSE,;t t
 s,@BUILD_BOOST_TRUE@,$BUILD_BOOST_TRUE,;t t
